name: Cypress end to end testing
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install pnpm dependencies, cache them correctly
      - name: Install pnpm
        run: npm install -g pnpm@8

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6.1.0
        with:
          start: pnpm start
